global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'api_nestjs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api_nestjs:3000']
        labels:
          service: 'core-api'
          env: 'prod'

  - job_name: 'api_fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api_fastapi:8000']
        labels:
          service: 'analytics-api'
          env: 'prod'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          env: 'prod'

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'nginx-exporter'
          env: 'prod'

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres-exporter'
          env: 'prod'

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis-exporter'
          env: 'prod'

  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
        labels:
          service: 'rabbitmq-exporter'
          env: 'prod'

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://nginx
          - http://api_nestjs:3000/health
          - http://api_fastapi:8000/health
    relabel_configs:
      - source_labels: [__address__]
        target: __param_target
      - source_labels: [__param_target]
        target: instance
      - target: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - postgresql:5432
          - redis:6379
          - rabbitmq:5672
          - grafana:3000
          - prometheus:9090
    relabel_configs:
      - source_labels: [__address__]
        target: __param_target
      - source_labels: [__param_target]
        target: instance
      - target: __address__
        replacement: blackbox-exporter:9115