groups:
  - name: postgres-alerts
    rules:
      - alert: PostgresConnectionsHigh
        expr: pg_stat_activity_count{datname="AUTOMACAO"} > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of connections on {{ $labels.datname }}"
          description: "Active connections exceed 80 for 5 minutes."

      - alert: PostgresWaitLocksHigh
        expr: sum by (instance) (pg_wait_sampling_event_count{event="Lock"}) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High lock waits on {{ $labels.instance }}"
          description: "Wait sampling shows lock events > 1000 samples in 10m."