version: '3.9'

networks:
  cmm_network:
    driver: bridge

services:
  nginx:
    image: nginx:1.28.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /opt/docker/certificados/cmm_am_gov_br_inter.crt:/etc/ssl/certs/server.crt:ro
      - /opt/docker/certificados/cmm_am_gov_br.key:/etc/ssl/certs/server.key:ro
    networks:
      - cmm_network
    depends_on:
      - frontend
    environment:
      - TZ=America/Manaus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    container_name: frontend
    restart: unless-stopped
    networks:
      - cmm_network
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production