networks:
  cmm_network:
    driver: bridge

services:
  nginx:
    build:
      context: ./Backend/nginx
      dockerfile: Dockerfile
    container_name: NGINX
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
      - /opt/docker/certificados/cmm_am_gov_br_inter.crt:/etc/ssl/certs/server.crt:ro
      - /opt/docker/certificados/cmm_am_gov_br.key:/etc/ssl/certs/server.key:ro
    networks:
      - cmm_network
    depends_on:
      frontend:
        condition: service_started
      api_nestjs:
        condition: service_started
      api_fastapi:
        condition: service_started
      postgresql:
        condition: service_started
    environment:
      - TZ=America/Manaus
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || wget -q -S --spider http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  api_nestjs:
    build:
      context: ./Backend/NestJS
      dockerfile: Dockerfile
    container_name: NESTJS
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - cmm_network
    depends_on:
      postgresql:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=America/Manaus
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318/v1/traces
      - JWT_SECRET=dev-secret
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - AUTO_RELOAD=false

  api_fastapi:
    build:
      context: ./Backend/FastAPI
      dockerfile: Dockerfile
    container_name: FASTAPI
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "8001:8000"
    networks:
      - cmm_network
    environment:
      - TZ=America/Manaus
      - AUTO_RELOAD=false
      - DB_PATH=/app/discovery.db
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || wget -q -S --spider http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: FRONTEND
    restart: unless-stopped
    networks:
      - cmm_network
    expose:
      - "80"
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_PROMETHEUS_URL=/prometheus
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || wget -q -S --spider http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgresql:
    build:
      context: ./Backend/postgresql
      dockerfile: Dockerfile
    container_name: POSTGRESQL
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - cmm_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - TZ=America/Manaus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: PROMETHEUS
    restart: unless-stopped
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - ./Backend/prometheus:/etc/prometheus:ro
    command: --config.file=/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9090/-/healthy || wget -q -S --spider http://localhost:9090/-/healthy || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - cmm_network

  redis:
    image: redis:latest
    container_name: REDIS
    restart: unless-stopped
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - cmm_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - TZ=America/Manaus
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RABBITMQ
    restart: unless-stopped
    expose:
      - "5672"
      - "15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cmm_network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=America/Manaus
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  grafana:
    image: grafana/grafana:latest
    container_name: GRAFANA
    restart: unless-stopped
    expose:
      - "3000"
    ports:
      - "3010:3000"
    depends_on:
      prometheus:
        condition: service_started
      loki:
        condition: service_started
      tempo:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/api/health || wget -q -S --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - cmm_network
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./Backend/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./Backend/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./Backend/grafana/dashboards:/var/lib/grafana/dashboards:ro

  loki:
    image: grafana/loki:2.9.4
    container_name: LOKI
    restart: unless-stopped
    expose:
      - "3100"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3100/ready || wget -q -S --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    networks:
      - cmm_network

  promtail:
    image: grafana/promtail:2.9.4
    container_name: PROMTAIL
    restart: unless-stopped
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./Backend/promtail:/etc/promtail:ro
    command: -config.file=/etc/promtail/config.yml
    expose:
      - "9080"
    ports:
      - "9080:9080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9080/ready || wget -q -S --spider http://localhost:9080/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s
    depends_on:
      loki:
        condition: service_started
    networks:
      - cmm_network

  tempo:
    image: grafana/tempo:latest
    container_name: TEMPO
    restart: unless-stopped
    expose:
      - "3200"
      - "4318"
    ports:
      - "3400:3200"
      - "4318:4318"
    networks:
      - cmm_network
    volumes:
      - ./Backend/tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro
    command: -config.file=/etc/tempo/tempo.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3200/metrics || wget -q -S --spider http://localhost:3200/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 45s

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: CADVISOR
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8800:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/metrics || wget -q -S --spider http://localhost:8080/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cmm_network
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: NGINX-EXPORTER
    restart: unless-stopped
    command: --nginx.scrape-uri=http://nginx/nginx_status
    expose:
      - "9113"
    ports:
      - "9113:9113"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9113/metrics || wget -q -S --spider http://localhost:9113/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cmm_network
    depends_on:
      - nginx

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: POSTGRES-EXPORTER
    restart: unless-stopped
    environment:
      - DATA_SOURCE_NAME=postgresql://admin:admin@postgresql:5432/postgres?sslmode=disable
    expose:
      - "9187"
    ports:
      - "9187:9187"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9187/metrics || wget -q -S --spider http://localhost:9187/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cmm_network
    depends_on:
      - postgresql

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: REDIS-EXPORTER
    restart: unless-stopped
    expose:
      - "9121"
    ports:
      - "9121:9121"
    command: ["--redis.addr=redis://redis:6379"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9121/metrics || wget -q -S --spider http://localhost:9121/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cmm_network
    depends_on:
      - redis

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: RABBITMQ-EXPORTER
    restart: unless-stopped
    expose:
      - "9419"
    ports:
      - "9419:9419"
    environment:
      - RABBITMQ_URL=http://rabbitmq:15672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9419/metrics || wget -q -S --spider http://localhost:9419/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cmm_network
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
    driver: local
  nginx_logs:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local