version: '3.9'

services:
  frontend-builder:
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend_dist:/dist
    command: >
      sh -c "
        npm install &&
        npm run dev
      "