version: '3.9'

networks:
  cmm_network:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      no_cache: true
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - cmm_network
    depends_on:
      - frontend
    environment:
      - TZ=America/Manaus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    container_name: frontend
    restart: unless-stopped
    networks:
      - cmm_network
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production