global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_by: ['alertname','service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://api_nestjs:3000/events/alerts'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match_re:
      severity: 'warning|info'
    equal: ['alertname','service']